version: '3.8'

services:
  tetris-game:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - tetris-data:/app/instance
    environment:
      - FLASK_ENV=production
    restart: unless-stopped

volumes:
  tetris-data: